services:
  indigo:
    image: epmlsop/indigo-service:latest
    container_name: indigo_service
    ports:
      - "8002:80"

  ias-react-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ias_react_demo
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - C:/certs/cm-local:/etc/nginx/certs:ro
    depends_on:
      - indigo